<?php

namespace App\Http\Controllers\Api\Maintenance;

use App\Http\Controllers\Api\BaseController;
use App\Http\Requests\Maintenance\StoreEquipmentRequest;
use App\Models\Equipment;
use Illuminate\Http\Request;

use App\Http\Requests\Maintenance\UpdateEquipmentRequest;
use App\Http\Requests\Maintenance\ReportBrokenEquipmentRequest;

class EquipmentController extends BaseController
{
    public function index(Request $request)
    {
        $query = Equipment::with('workCenter:id,name,code')
            ->applyStandardFilters(
                $request,
                ['name', 'code', 'notes'], // Searchable
                ['status', 'work_center_id'] // Filterable
            );

        if ($request->boolean('maintenance_due')) {
            $query->where('next_maintenance', '<=', now());
        }

        $counts = $this->getStatusCounts(Equipment::query(), 'status');

        return $this->respondWithPagination(
            $query->paginate($request->get('per_page', 10)),
            ['counts' => $counts]
        );
    }

    public function store(StoreEquipmentRequest $request)
    {
        $validated = $request->validated();

        // Set initial next maintenance date
        if (isset($validated['maintenance_interval_days'])) {
            $validated['next_maintenance'] = now()->addDays($validated['maintenance_interval_days']);
        }

        $equipment = Equipment::create($validated);

        return $this->success($equipment, [], 201);
    }

    public function show(Equipment $equipment)
    {
        return $this->success(
            $equipment->load(['workCenter', 'maintenanceLogs.performer'])
        );
    }

    public function update(UpdateEquipmentRequest $request, Equipment $equipment)
    {
        $equipment->update($request->validated());

        return $this->success($equipment);
    }

    public function destroy(Equipment $equipment)
    {
        $equipment->delete();

        return $this->success(null, [], 204);
    }

    // Report equipment as broken
    public function reportBroken(ReportBrokenEquipmentRequest $request, Equipment $equipment)
    {
        $equipment->update(['status' => 'broken']);

        // Create open maintenance request
        $maintenanceRequest = \App\Models\MaintenanceRequest::create([
            'equipment_id' => $equipment->id,
            // 'name' is auto-generated by model boot
            'description' => $request->validated()['description'],
            'priority' => $request->validated()['priority'] ?? 'normal',
            'status' => 'confirmed',
            'request_type' => 'corrective',
            'requested_by' => $request->user()->id,
        ]);

        return $this->success([
            'equipment' => $equipment,
            'maintenance_request' => $maintenanceRequest
        ], ['message' => 'Equipment reported as broken']);
    }
}
