<?php

namespace App\Http\Controllers\Api\Maintenance;

use App\Http\Controllers\Controller;
use App\Http\Requests\Maintenance\LogMaintenanceRequest;
use App\Http\Requests\Maintenance\StoreEquipmentRequest;
use App\Models\Equipment;
use App\Models\MaintenanceLog;
use Illuminate\Http\Request;

use App\Http\Requests\Maintenance\UpdateEquipmentRequest;
use App\Http\Requests\Maintenance\ReportBrokenEquipmentRequest;

class EquipmentController extends Controller
{
    public function index(Request $request)
    {
        $query = Equipment::with('workCenter');

        if ($request->has('status')) {
            $query->where('status', $request->status);
        }
        if ($request->has('work_center_id')) {
            $query->where('work_center_id', $request->work_center_id);
        }
        if ($request->boolean('maintenance_due')) {
            $query->where('next_maintenance', '<=', now());
        }

        return response()->json(
            $query->orderBy('name')->paginate($request->get('per_page', 10))
        );
    }

    public function store(StoreEquipmentRequest $request)
    {
        $validated = $request->validated();

        // Set initial next maintenance date
        if (isset($validated['maintenance_interval_days'])) {
            $validated['next_maintenance'] = now()->addDays($validated['maintenance_interval_days']);
        }

        $equipment = Equipment::create($validated);

        return response()->json($equipment, 201);
    }

    public function show(Equipment $equipment)
    {
        return response()->json(
            $equipment->load(['workCenter', 'maintenanceLogs.performer'])
        );
    }

    public function update(UpdateEquipmentRequest $request, Equipment $equipment)
    {
        $equipment->update($request->validated());

        return response()->json($equipment);
    }

    public function destroy(Equipment $equipment)
    {
        $equipment->delete();

        return response()->json(null, 204);
    }

    // Report equipment as broken
    public function reportBroken(ReportBrokenEquipmentRequest $request, Equipment $equipment)
    {
        $equipment->update(['status' => 'broken']);

        // Create open maintenance request
        $maintenanceRequest = \App\Models\MaintenanceRequest::create([
            'equipment_id' => $equipment->id,
            // 'name' is auto-generated by model boot
            'description' => $request->validated()['description'],
            'priority' => $request->validated()['priority'] ?? 'normal',
            'status' => 'confirmed',
            'request_type' => 'corrective',
            'requested_by' => $request->user()->id,
        ]);

        return response()->json([
            'equipment' => $equipment,
            'maintenance_request' => $maintenanceRequest
        ]);
    }
}
