<?php

namespace App\Http\Controllers\Api\Maintenance;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\Maintenance\StoreMaintenanceRequestRequest;
use App\Http\Requests\Maintenance\UpdateMaintenanceRequestRequest;
use App\Models\MaintenanceRequest;

class MaintenanceRequestController extends Controller
{
    public function index(Request $request)
    {
        $query = MaintenanceRequest::with(['equipment', 'requester', 'assignee']);

        if ($request->has('status')) {
            $query->where('status', $request->status);
        }
        if ($request->has('equipment_id')) {
            $query->where('equipment_id', $request->equipment_id);
        }

        return response()->json($query->orderBy('created_at', 'desc')->paginate($request->get('per_page', 10)));
    }

    public function store(StoreMaintenanceRequestRequest $request)
    {
        $data = $request->validated();
        $data['requested_by'] = $request->user()->id;

        // Name is auto-generated by model boot method

        $maintenanceRequest = MaintenanceRequest::create($data);
        return response()->json($maintenanceRequest, 201);
    }

    public function show(MaintenanceRequest $maintenanceRequest)
    {
        return response()->json($maintenanceRequest->load(['equipment', 'requester', 'assignee']));
    }

    public function update(UpdateMaintenanceRequestRequest $request, string $id)
    {
        $maintenanceRequest = MaintenanceRequest::findOrFail($id);
        $validated = $request->validated();
        $maintenanceRequest->update($validated);

        // Explicitly reload model to ensure fields are available (fix for potential binding issue)
        $mtRequest = MaintenanceRequest::findOrFail($maintenanceRequest->id);

        // If corrective maintenance is done, set equipment back to operational
        if (($validated['status'] ?? '') === 'done' && $mtRequest->request_type === 'corrective') {
            $mtRequest->equipment->update(['status' => 'operational']);
        }

        return response()->json($maintenanceRequest);
    }

    public function destroy(MaintenanceRequest $maintenanceRequest)
    {
        $maintenanceRequest->delete();
        return response()->noContent();
    }
}
