<?php

namespace App\Http\Controllers\Api\Maintenance;

use App\Http\Controllers\Api\BaseController;
use Illuminate\Http\Request;
use App\Http\Requests\Maintenance\StoreMaintenanceRequestRequest;
use App\Http\Requests\Maintenance\UpdateMaintenanceRequestRequest;
use App\Models\MaintenanceRequest;

class MaintenanceRequestController extends BaseController
{
    public function index(Request $request)
    {
        $query = MaintenanceRequest::with(['equipment', 'requester', 'assignee'])
            ->applyStandardFilters(
                $request,
                ['name', 'description'], // Searchable
                ['status', 'equipment_id', 'priority', 'request_type', 'assigned_to'] // Filterable
            );

        $counts = $this->getStatusCounts(MaintenanceRequest::query(), 'status');

        return $this->respondWithPagination(
            $query->paginate($request->get('per_page', 10)),
            ['counts' => $counts]
        );
    }

    public function store(StoreMaintenanceRequestRequest $request)
    {
        $data = $request->validated();
        $data['requested_by'] = $request->user()->id;

        // Name is auto-generated by model boot method

        $maintenanceRequest = MaintenanceRequest::create($data);
        return $this->success($maintenanceRequest, [], 201);
    }

    public function show(MaintenanceRequest $maintenanceRequest)
    {
        return $this->success(
            $maintenanceRequest->load(['equipment', 'requester', 'assignee'])
        );
    }

    public function update(UpdateMaintenanceRequestRequest $request, string $id)
    {
        $maintenanceRequest = MaintenanceRequest::findOrFail($id);
        $validated = $request->validated();
        $maintenanceRequest->update($validated);

        // Explicitly reload model to ensure fields are available (fix for potential binding issue)
        $mtRequest = MaintenanceRequest::findOrFail($maintenanceRequest->id);

        // If corrective maintenance is done, set equipment back to operational
        if (($validated['status'] ?? '') === 'done' && $mtRequest->request_type === 'corrective') {
            $mtRequest->equipment->update(['status' => 'operational']);
        }

        return $this->success($maintenanceRequest);
    }

    public function destroy(MaintenanceRequest $maintenanceRequest)
    {
        $maintenanceRequest->delete();
        return $this->success(null, [], 204);
    }
}
